### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by odiferousmint** [AmirAlmasi/Bit-Torrent-Erlang-#1]
Hello. What is the status of this project? How incomplete is it? What are the missing features? How does it compare to today's protocols and whatnot?

**Comment by AmirAlmasi** [comment]
Hi, this project is not maintained anymore. Unfortunately, don't know the changes in the protocol (if there are any).

**Comment by odiferousmint** [comment]
I see, that is quite unfortunate.
